#!/usr/bin/env ruby
# -*- coding: utf-8 -*-
require "logger"
require "json"

require_relative "lib/rest.rb"
require_relative "conf/config.rb"
config = $config
log = Logger.new("log/gddns.log")
log.level = Logger::WARN

# Get Domain ID & Resource ID
